// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    return {
      genID: (function() {
        var id;
        id = 0;
        return function() {
          return id++;
        };
      })(),
      createRNG: function(seed) {
        seed = ~~seed;
        return function() {
          return (seed = (seed * 16807) % 2147483647) / 2147483647;
        };
      },
      createRNGSeed: function() {
        return ~~(Math.random() * 2147483647);
      },
      clamp: function(n, min, max) {
        if (n < min) {
          return min;
        } else if (n > max) {
          return max;
        } else {
          return n;
        }
      },
      loadImages: function(srcs, callback) {
        var loadNextImage, result;
        result = [];
        loadNextImage = function() {
          var img;
          if (srcs.length === result.length) {
            callback(result);
          } else {
            img = new Image();
            img.src = srcs[result.length];
            img.onload = function() {
              result.push(img);
              return loadNextImage();
            };
          }
          return null;
        };
        return loadNextImage();
      }
    };
  });

}).call(this);
